// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIckrbcLioSq7ZRYFGlLCmopRzfhDYgvs',
    appId: '1:181152304530:web:be58d7cc8f286982b7454b',
    messagingSenderId: '181152304530',
    projectId: 'todoapp-d0c22',
    authDomain: 'todoapp-d0c22.firebaseapp.com',
    storageBucket: 'todoapp-d0c22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQ6TuS5TU6RR6GjlPZz-wrb_gL-RRouM',
    appId: '1:181152304530:android:dd5464038def38dfb7454b',
    messagingSenderId: '181152304530',
    projectId: 'todoapp-d0c22',
    storageBucket: 'todoapp-d0c22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT9LCHfRnIyGrsoWIS0Gb38TRw-CzhoT0',
    appId: '1:181152304530:ios:d61291885859db87b7454b',
    messagingSenderId: '181152304530',
    projectId: 'todoapp-d0c22',
    storageBucket: 'todoapp-d0c22.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT9LCHfRnIyGrsoWIS0Gb38TRw-CzhoT0',
    appId: '1:181152304530:ios:d61291885859db87b7454b',
    messagingSenderId: '181152304530',
    projectId: 'todoapp-d0c22',
    storageBucket: 'todoapp-d0c22.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIckrbcLioSq7ZRYFGlLCmopRzfhDYgvs',
    appId: '1:181152304530:web:013c2b7d46bc6a68b7454b',
    messagingSenderId: '181152304530',
    projectId: 'todoapp-d0c22',
    authDomain: 'todoapp-d0c22.firebaseapp.com',
    storageBucket: 'todoapp-d0c22.appspot.com',
  );
}
